backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

  
media_folder: "/assets/media"
public_folder: "/assets/media"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "main" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "Main Page" # Used in the UI
    identifier_field: page
    folder: "/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter: {field: "title", value: "Main"}
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # Lesson
      - label: "Title"
        name: "title"
        widget: "string"
      # Text
      - label: "Text" 
        name: "body" 
        widget: "markdown" 
        required: false
      - label: 'layout'
        name: 'layout'
        widget: 'hidden'
        default: 'base.njk'
  - name: "introduction" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "Introduction" # Used in the UI
    identifier_field: page
    folder: "/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter: {field: "title", value: "Introduction"}
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Text" 
        name: "body" 
        widget: "markdown" 
        required: false
      - label: 'layout'
        name: 'layout'
        widget: 'hidden'
        default: 'base.njk'
  - name: "further-reading" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "Further Reading" # Used in the UI
    identifier_field: page
    folder: "/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter: {field: "title", value: "Further Reading"}
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # Lesson
      - label: "Title"
        name: "title"
        widget: "string"
      # Text
      - label: "Text" 
        name: "body" 
        widget: "markdown" 
        required: false
      - label: 'layout'
        name: 'layout'
        widget: 'hidden'
        default: 'base.njk'
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "About" # Used in the UI
    identifier_field: page
    folder: "/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter: {field: "title", value: "About"}
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # Lesson
      - label: "Title"
        name: "title"
        widget: "string"
      # Text
      - label: "Text" 
        name: "body" 
        widget: "markdown" 
        required: false
      - label: 'layout'
        name: 'layout'
        widget: 'hidden'
        default: 'base.njk'
  - name: "essay" 
    editor:
      preview: false
    label: "Essay" 
    identifier_field: essay
    folder: "essay" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # Lesson
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Latitude"
        name: "lat"
        widget: "number"
        value_type: "float"
        step: 0
      - label: "Longitude"
        name: "long"
        widget: "number"
        value_type: "float"
        step: 0
      # Text
      - label: "Text" 
        name: "body" 
        widget: "markdown" 
        required: false  
      - label: "Topic" 
        name: "topic" 
        widget: "string" 
        required: false
