backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

  
media_folder: "/assets/media"
public_folder: "/assets/media"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "main" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: true
    label: "Main Page" # Used in the UI
    identifier_field: page
    folder: "/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter: {field: "title", value: "Main"}
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # Lesson
      - label: "Title"
        name: "title"
        widget: "string"
      # Text
      - label: "Text" 
        name: "body" 
        widget: "markdown" 
        required: false
  - name: "main" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: true
    label: "Introduction" # Used in the UI
    identifier_field: page
    folder: "/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter: {field: "title", value: "Main"}
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Text" 
        name: "body" 
        widget: "markdown" 
        required: false
  - name: "essay" 
    editor:
      preview: true
    label: "Essay" 
    identifier_field: essay
    folder: "essay" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # Lesson
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Latitude"
        name: "lat"
        widget: "number"
      - label: "Longitude"
        name: "long"
        widget: "number"
      # Text
      - label: "Text" 
        name: "body" 
        widget: "markdown" 
        required: false  
